version: '3'

services:
  api-solid-pg:
    image: postgres:13
    ports: 
      - 5432:5432
    environment:
        - POSTGRES_USER=docker
        - POSTGRES_PASSWORD=dcoker
        - POSTGRES_DB=apisolid

